services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  JosefGlatz\HideSysTemplate\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  JosefGlatz\HideSysTemplate\EventListener\RenderFlashMessage:
    tags:
      - name: event.listener
        identifier: 'josefglatz/hide-sys-template/renderFlashMessage'
        event: TYPO3\CMS\Backend\Controller\Event\BeforeFormEnginePageInitializedEvent
        before: 'legacy-slot'